import importlib.util
import json
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stderr
from io import BytesIO, StringIO
from pathlib import Path
from unittest.mock import patch
import zipfile


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "extract_markdown.py"
SPEC = importlib.util.spec_from_file_location("extract_markdown", SCRIPT)
extract_markdown = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = extract_markdown
SPEC.loader.exec_module(extract_markdown)


def make_pdf(path: Path, text: str | None = "sample") -> None:
    import pymupdf

    document = pymupdf.open()
    page = document.new_page()
    if text:
        page.insert_text((72, 72), text)
    document.save(path)
    document.close()


class ExtractMarkdownTests(unittest.TestCase):
    def test_mineru_extract_writes_markdown_and_relative_image(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            archive = BytesIO()
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("full.md", "# Parsed\n\n![](images/fig.png)\n")
                zipped.writestr("images/fig.png", b"figure")
            calls = []

            def request_json(method, endpoint, payload=None):
                calls.append((method, endpoint))
                if method == "POST":
                    return {"batch_id": "batch-1", "file_urls": ["https://signed.invalid/upload?sig=secret"]}
                return {"extract_result": [{"data_id": payload_id, "state": "done",
                                           "full_zip_url": "https://signed.invalid/result?sig=secret"}]}

            # The request data_id is generated by extract_many from the input identity.
            payload_id = extract_markdown._pdf_identity(pdf, "mineru", "vlm")[1]["identity"][:32]
            with patch.object(extract_markdown.MinerUExtractor, "_request_json", side_effect=request_json), \
                 patch.object(extract_markdown.MinerUExtractor, "_upload") as upload, \
                 patch.object(extract_markdown.MinerUExtractor, "_download_zip", return_value=archive.getvalue()):
                result = extract_markdown.extract_many([pdf], root / "out", api_token="unit-test-token")
            self.assertEqual(result["results"][0]["status"], "extracted")
            markdown = Path(result["results"][0]["markdown_path"])
            self.assertIn("images/fig.png", markdown.read_text(encoding="utf-8"))
            self.assertEqual((markdown.parent / "images/fig.png").read_bytes(), b"figure")
            upload.assert_called_once()
            self.assertEqual([call[0] for call in calls], ["POST", "GET"])
            manifest_text = Path(result["manifest"]).read_text(encoding="utf-8")
            self.assertNotIn("sig=secret", manifest_text)
            self.assertNotIn("unit-test-token", manifest_text)

    def test_pending_batch_resumes_polling_and_completed_item_is_skipped(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            _folder, source = extract_markdown._pdf_identity(pdf, "mineru", "vlm")
            (root / "out").mkdir()
            manifest = {"version": 1, "results": [{**source, "status": "needs_attention",
                        "batch_id": "pending-batch", "reason": "mineru_timeout", "backend": "mineru"}]}
            (root / "out" / "markdown-manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
            archive = BytesIO()
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("full.md", "# Resumed\n")
            with patch.object(extract_markdown.MinerUExtractor, "_request_json",
                              return_value={"extract_result": [{"data_id": source["identity"][:32],
                                                                 "state": "done", "full_zip_url": "unused"}]}) as request, \
                 patch.object(extract_markdown.MinerUExtractor, "_upload",
                              side_effect=AssertionError("pending batch must not upload again")) as upload, \
                 patch.object(extract_markdown.MinerUExtractor, "_download_zip",
                              return_value=archive.getvalue()):
                result = extract_markdown.extract_many([pdf], root / "out", api_token="test-token")
            self.assertEqual(result["results"][0]["status"], "extracted")
            self.assertEqual(request.call_args.args[:2], ("GET", "extract-results/batch/pending-batch"))
            upload.assert_not_called()
            with patch.object(extract_markdown.MinerUExtractor, "_request_json",
                              side_effect=AssertionError("completed item must not call MinerU")):
                resumed = extract_markdown.extract_many([pdf], root / "out", api_token="test-token")
            self.assertEqual(resumed["results"][0]["status"], "already_present")

    def test_missing_token_does_not_make_network_request(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            with patch.dict(os.environ, {"MINERU_API_TOKEN": ""}), \
                 patch("urllib.request.urlopen", side_effect=AssertionError("network call")):
                result = extract_markdown.extract_many([pdf], root / "out", backend="mineru")
            self.assertEqual(result["results"][0]["status"], "needs_attention")
            self.assertEqual(result["results"][0]["reason"], "missing_mineru_token")

    def test_zip_traversal_is_rejected(self):
        archive = BytesIO()
        with zipfile.ZipFile(archive, "w") as zipped:
            zipped.writestr("full.md", "# parsed")
            zipped.writestr("../escape.txt", "unsafe")
        with self.assertRaisesRegex(RuntimeError, "unsafe_zip_path"):
            extract_markdown.MinerUExtractor._unpack(archive.getvalue())

    def test_corrupt_checkpoint_is_preserved_and_cli_reports_short_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            output = root / "out"
            output.mkdir()
            manifest = output / "markdown-manifest.json"
            original = b"{this is not json"
            manifest.write_bytes(original)
            error_output = StringIO()
            with redirect_stderr(error_output):
                code = extract_markdown.main([str(pdf), "--output", str(output)])
            self.assertEqual(code, 2)
            self.assertEqual(manifest.read_bytes(), original)
            self.assertIn("invalid JSON", error_output.getvalue())

    def test_missing_recorded_image_reextracts_to_suffix_and_manifest_paths_resolve(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            output = root / "out"
            folder_name, source = extract_markdown._pdf_identity(pdf, "mineru", "vlm")
            old_folder = output / folder_name
            (old_folder / "images").mkdir(parents=True)
            old_markdown = old_folder / "full.md"
            old_markdown.write_text("# User's existing artifact\n", encoding="utf-8")
            manifest = {"version": 1, "results": [{**source, "status": "extracted",
                        "markdown_path": str(old_markdown), "image_paths": ["images/figure.png"],
                        "backend": "mineru"}]}
            (output / "markdown-manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
            input_dir = root / "input-list"
            input_dir.mkdir()
            input_manifest = input_dir / "items.json"
            input_manifest.write_text(json.dumps({"version": 1, "items": [{
                "status": "downloaded", "path": "../paper.pdf"}]}), encoding="utf-8")
            self.assertEqual(extract_markdown._load_manifest_inputs(input_manifest), [pdf.resolve()])

            archive = BytesIO()
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("full.md", "# Re-extracted\n![](images/figure.png)\n")
                zipped.writestr("images/figure.png", b"new image")
            payload_id = source["identity"][:32]
            responses = [
                {"batch_id": "batch-new", "file_urls": ["https://signed.invalid/upload"]},
                {"extract_result": [{"data_id": payload_id, "state": "done",
                                     "full_zip_url": "https://signed.invalid/result"}]},
            ]
            with patch.object(extract_markdown.MinerUExtractor, "_request_json",
                              side_effect=responses), \
                 patch.object(extract_markdown.MinerUExtractor, "_upload"), \
                 patch.object(extract_markdown.MinerUExtractor, "_download_zip",
                              return_value=archive.getvalue()):
                result = extract_markdown.extract_many([pdf], output, api_token="test-token")
            markdown = Path(result["results"][0]["markdown_path"])
            self.assertEqual(result["results"][0]["status"], "extracted")
            self.assertEqual(markdown.parent.name, f"{folder_name}-2")
            self.assertEqual(old_markdown.read_text(encoding="utf-8"), "# User's existing artifact\n")
            image_relative = result["results"][0]["image_paths"][0]
            self.assertTrue((markdown.parent / image_relative).is_file())

    def test_same_name_pdfs_get_distinct_outputs_and_blank_local_pdf_needs_attention(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            first, second, blank = root / "a" / "paper.pdf", root / "b" / "paper.pdf", root / "blank.pdf"
            first.parent.mkdir()
            second.parent.mkdir()
            make_pdf(first, "first paper")
            make_pdf(second, "second paper")
            make_pdf(blank, None)
            result = extract_markdown.extract_many([first, second, blank], root / "out", backend="local")
            self.assertEqual([item["status"] for item in result["results"]],
                             ["extracted", "extracted", "needs_attention"])
            self.assertEqual(result["results"][2]["reason"], "no_extractable_text")
            self.assertNotEqual(result["results"][0]["markdown_path"],
                                result["results"][1]["markdown_path"])
            self.assertEqual(result["failed"], 1)

    def test_dry_run_does_not_read_token_or_create_output(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pdf = root / "paper.pdf"
            make_pdf(pdf)
            output = root / "out"
            with patch.dict(os.environ, {"MINERU_API_TOKEN": ""}), \
                 patch("urllib.request.urlopen", side_effect=AssertionError("network call")):
                result = extract_markdown.extract_many([pdf], output, dry_run=True)
            self.assertEqual(result["results"][0]["status"], "planned")
            self.assertFalse(output.exists())


if __name__ == "__main__":
    unittest.main()
